name: CICD
on:
  push:
    branches: [dev, master]

jobs:
  cicd:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          aws-region: us-east-1

      - name: Install dependencies
        run: npm install

      - name: Run linter
        run: npm run lint

      - name: Package
        run: CI= npm run build

      - name: Deploy to dev
        if: endsWith(github.ref, '/dev')
        run: aws s3 sync dist/ s3://${{secrets.TEST_S3_BUCKET}}

      - name: Deploy to prod
        if: endsWith(github.ref, '/master')
        run: aws s3 sync dist/ s3://${{secrets.PROD_S3_BUCKET}}
